#!/usr/bin/env sh

PROG_NAME=$(basename "$0")
BASE="/working"
IMAGES="$BASE/images"
OUTPUT="$BASE/output"
SPARSE="$OUTPUT/sparse"
DENSE="$OUTPUT/dense"

MODEL_ID="0"
NUM_ITERATIONS="2"
WINDOW_STEP="2"
FILTER="true"
GEOM_CONSISTENCY="false"

print_config() {
    cat <<EOF | sed -E '/^$/d' >&2
==========================================
MODEL       : $MODEL_ID
ITERATION   : $NUM_ITERATIONS
STEP        : $WINDOW_STEP
FILTER      : $FILTER
CONSISTENCY : $GEOM_CONSISTENCY
==========================================
EOF
}

print_usage() {
        cat <<EOF >&2
$PROG_NAME [OPTION]...
Rodones COLMAP multi-view stereo script
Options:
  -m, --model=ID                  sparse model id. (default: $MODEL_ID)
  -i, --iterations=N              number of iterations performed by patch_match_stereo step. (default: $NUM_ITERATIONS)
  -s, --step=N                    window step count performed by patch_match_stereo step. (default: $WINDOW_STEP)
  -f, --filter[=N]                enable filtering for patch_match_stereo step. (default: $FILTER)
  -c, --consistency[=N]           enable geometric consistency for patch_match_stereo step. (default: $GEOM_CONSISTENCY)
EOF
}

OPTIONS=$(getopt -n "$PROG_NAME" -o hm:i:s:f::c:: -l help,model:,iteration:,step:,filter::,consistency:: -- "$@")

eval set -- "$OPTIONS"

while [ $# -gt 0 ]; do
    case $1 in
    -h | --help)
        print_usage
        exit
        ;;
    -m | --model)
        MODEL_ID="$2"
        [ ! -d "$SPARSE/$MODEL_ID" ] && echo "error: model does not exist." && exit 1
        shift 2
        ;;
    -i | --iteration)
        NUM_ITERATIONS="$2"
        shift 2
        ;;
    -s | --step)
        WINDOW_STEP="$2"
        shift 2
        ;;
    -f | --filter)
        FILTER="${2:-true}"
        shift 2
        ;;
    -c | --consistency)
        GEOM_CONSISTENCY="${2:-true}"
        shift 2
        ;;
    --)
        shift
        break
        ;;
    *)
        shift
        ;;
    esac
done

print_config

# [ -d "$OUTPUT" ] || mkdir "$OUTPUT"
# [ -d "$DENSE" ] || mkdir "$DENSE"

echo colmap image_undistorter \
    --image_path "$IMAGES" \
    --input_path "$SPARSE/$MODEL_ID" \
    --output_path "$DENSE" \
    --output_type COLMAP \
    --max_image_size 1000

echo colmap patch_match_stereo \
    --workspace_path "$DENSE" \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency "$GEOM_CONSISTENCY" \
    --PatchMatchStereo.filter "$FILTER" \
    --PatchMatchStereo.window_step "$WINDOW_STEP" \
    --PatchMatchStereo.num_iterations "$NUM_ITERATIONS"

echo colmap stereo_fusion \
    --workspace_path "$DENSE" \
    --workspace_format COLMAP \
    --input_type photometric \
    --output_path "$DENSE/fused-$MODEL_ID.ply"
