#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

print_help() {
  cat <<EOF
Usage: $(basename "$0") SCRIPT WORKSPACE [ARGS]
rodones script executor 

available scripts:
$(find ./*.sh | sed "s/.sh//g;s/.\//   /g")
EOF
}

measure() {
  local CMD="$1"
  local LOGS="/working/logs"
  local ARGS="${*:1}"
  # shellcheck disable=SC2155
  local DATE="$(date +"%FT%H%M%z")"
  local NAME="$CMD""_""$DATE.txt"

  [ -d "$LOGS" ] || mkdir "$LOGS"

  time "$SCRIPT_DIR/$CMD" "$ARGS" | { tee "$LOGS/$NAME"; }
  
  echo "==========================================" | tee -a "$LOGS/$NAME"
  grep --color=never "Elapsed time:" "$LOGS/$NAME"  | tee -a "$LOGS/$NAME"
  echo "==========================================" | tee -a "$LOGS/$NAME"
}

if [ "$1" = "--help" ]; then
  print_help
else
  measure "$@"
fi
