#!/usr/bin/env python3

from sys import path, argv
from os import listdir
from os.path import join

path.append("/colmap/scripts/python/")

from read_write_model import read_images_binary

argc = len(argv)
sparse = "/working/output/sparse"

for arg in argv[1:]:
  if not arg.isnumeric():
    print("error: expected number, found:", arg)
    exit(1)

source = argv[1:] if argc > 1 else listdir(sparse)
folders = [join(sparse, f) for f in source]
sparse_images = set()

for folder in folders:
  images = read_images_binary(join(folder, "images.bin")).values()

  for image in images:
    sparse_images.add(image.name)

working_images = set(listdir("/working/images"))
unused_images = sorted(working_images.difference(sparse_images))

for image in unused_images:
  print(image)
