FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-numpy \
    curl \
    s3cmd

ARG USERNAME=rodones
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $USERNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $USERNAME

COPY ./scripts /scripts
RUN chmod +x /scripts/*

ENV PATH="/scripts:${PATH}" \ 
    LANG="C.UTF-8" \
    PYTHONPATH="/colmap/scripts/python/:/scripts"

RUN echo 'export PS1="($WORKSPACE_NAME) $PS1"' >> "/home/$USERNAME/.bashrc"
