#!/usr/bin/env python3

import sqlite3
import numpy as np
from PIL import Image
from pathlib import Path


def blob_to_array(blob, dtype, shape=(-1,)):
    return np.fromstring(blob, dtype=dtype).reshape(*shape)


Path('/working/images-keypoints/').mkdir(parents=True, exist_ok=True)

db = sqlite3.connect("/working/output/database.db")
for image_id, name, data in db.execute(
        "SELECT kp.image_id, imgs.name, kp.data " +
        "FROM keypoints as kp JOIN images as imgs " +
        "ON imgs.image_id = kp.image_id"):
    print("({}) {}".format(image_id, name))
    keypoints = blob_to_array(data, np.float32, (-1, 2))
    img = Image.open("/working/images/"+name)

    for x, y in keypoints:
        if x <= 0 or y <= 0:
            continue
        x1, y1 = int(np.clip(x-3, 0, img.size[0])), int(np.clip(y-3, 0, img.size[1]))
        x2, y2 = int(np.clip(x+3, 0, img.size[0])), int(np.clip(y+3, 0, img.size[1]))

        for xx in range(x1, x2):
            for yy in range(y1, y2):
                img.putpixel((xx, yy), (255, 0, 0))

    img.save("/working/images-keypoints/"+name)

db.close()
