#!/usr/bin/env python3

import sqlite3
import numpy as np


def blob_to_array(blob, dtype, shape=(-1,)):
    return np.fromstring(blob, dtype=dtype).reshape(*shape)


db = sqlite3.connect("/working/output/database.db")

for image_id, name, data in db.execute(
        "SELECT kp.image_id, imgs.name, kp.data " +
        "FROM keypoints as kp " +
        "JOIN images as imgs " +
        "ON imgs.image_id = kp.image_id " +
        "ORDER BY kp.image_id"):
    print("{: 6}\t{}\t{}".format(image_id, name.ljust(30), len(blob_to_array(data, np.float32, (-1, 2)))))

db.close()
