---
- name: Prepare repositories
  hosts: all
  tasks:
    - name: Download docker repository key
      uri:
        url: https://download.docker.com/linux/ubuntu/gpg
        return_content: yes
      register: docker_keyring
    - name: Import docker repository key
      become: yes
      shell:
        cmd: gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        stdin: "{{ docker_keyring.content }}"
    - name: Install docker repository
      shell:
        cmd: >
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Update repositories
      become: yes
      apt:
        update_cache: yes
- name: Install dependencies
  hosts: all
  tasks:
    - name: Install packages using package manager
      become: yes
      package:
        name:
          - python3-docker
          - daemonize
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - s4cmd
        state: present
- name: Configure docker
  hosts: all
  tasks:
  - name: Create docker group
    group:
      name: docker
      state: present
  - name: Add user to docker group
    become: yes
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  - name: Enable docker service
    systemd:
      name: docker.service
      enabled: yes
      masked: no
    become: yes
  - name: Enable containerd service
    systemd:
      name: containerd.service
      enabled: yes
      masked: no
    become: yes
- name: Prepare environment
  hosts: all
  tasks:
    - name: Pull workspace repository
      git:
        repo: https://github.com/rodones/scripts.git
        dest: ~/workspace
    - name: Copy .env file
      copy:
        src: ../.env
        dest: ~/workspace/.env
    - name: Download vocab-tree
      get_url:
        url: https://demuc.de/colmap/vocab_tree_flickr100K_words256K.bin
        dest: ~/workspace/docker/vocab-trees/256.bin
